[dev 4.0.1 -> staging] Add namespace support for Android
adobe/aepsdk_flutter pull request #107
Opened 2024-04-22 17:56 UTC by cacheung

- Add namespace support for Android Gradle 8.x requirement
- Update Flutter SDK support version to 3.x
- Update Sample App to use Grade 8.x
- Update GitHub issue_template
- Update plugins release version to 4.0.1 

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-22 20:02 UTC, yangyansong-adbe commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      Example:
Can we also suggest customers add the output of the `flutter doctor -v` command to the bug report?

2024-04-22 20:22 UTC, yangyansong-adbe commented
@cacheung 
https://github.com/adobe/aepsdk_flutter/blob/main/plugins/flutter_aepassurance/pubspec.lock.
I suggest that we delete the `pubspec.lock` files present in each plugin directory and ignore them in `.gitignore`.  The dependency lock file is usually controlled by the app developer, we should not include it in the plugin projects. 
cc @cdhoffmann @praveek

2024-04-23 16:21 UTC, yangyansong-adbe approved these changes

2024-04-23 16:59 UTC, cdhoffmann requested changes

2024-04-23 16:59 UTC, cdhoffmann commented on .github/workflows/dart.yml
> +          xcode-version: "15.2"
why are we changing this? We should build on the earliest version we support.

2024-04-23 16:59 UTC, cdhoffmann commented on plugins/flutter_aepassurance/android/build.gradle
Need to update the versions for all the plugins to 3

2024-04-23 21:31 UTC, dsoffiantini approved these changes

2024-04-23 21:39 UTC, cdhoffmann approved these changes

2024-04-23 21:58 UTC, merged